language: python

sudo: false

python:
    - 2.7

env:
    matrix:
        # Oscar 0.6
        - COMBO="django-oscar==0.6.5 Django==1.5.10"
        - COMBO="django-oscar==0.6.5 Django==1.6.7"
        # Oscar 0.7
        - COMBO="django-oscar==0.7.3 Django==1.5.10"
        - COMBO="django-oscar==0.7.3 Django==1.6.7"
        # Oscar 1.0
        - COMBO="django-oscar==1.0.1 Django==1.6.7"
        - COMBO="django-oscar==1.0.1 Django==1.7.3"

install:
    - pip install $COMBO -r requirements.txt
    - python setup.py develop

before_script:
    - psql -c 'CREATE DATABASE oscar_stores;' -U postgres
    - psql -c 'CREATE EXTENSION postgis;' -U postgres -d oscar_stores
    - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d oscar_stores

script:
    - coverage run ./runtests.py
